### ISSUE TITLE
not an issue, but

### ISSUE THREAD

**Issue by ChillyLV** [Nemirtingas/ingame_overlay#1]
i saw your bug here:
https://github.com/ocornut/imgui/issues/3857

it happens in most modern source games, and a temporary fix would be to change D3DSBT_ALL to D3DSBT_PIXELSTATE in imgui/backends/imgui_impl_dx9.cpp

from
` if (g_pd3dDevice->CreateStateBlock(D3DSBT_ALL, &d3d9_state_block) < 0) 
     return; `

to

`if (g_pd3dDevice->CreateStateBlock(D3DSBT_PIXELSTATE, &d3d9_state_block) < 0) 
     return;`

hope this helps :)

**Comment by Nemirtingas** [comment]
That is interesting. For now I'll stick with the "Capture" call as it fixed the thing. Thanks.

**Comment by KiNGKiMO** [comment]
@ChillyLV I've tried your workaround with Overcooked2, game crashes if you Alt+Tab while overlay is on.

**Comment by ChillyLV** [comment]
> @ChillyLV I've tried your workaround with Overcooked2, game crashes if you Alt+Tab while overlay is on.

it only works on source engine games, such as counter-strike, garrys mod, left 4 dead, etc, and the issue was originally posted with a video from black mesa, which is based on source engine

**Comment by KiNGKiMO** [comment]
The capture call fixed the issue without affecting other games, so it's better.
