### ISSUE TITLE
[Suggestion] Update ImGui window size when hook state becomes `Reset`

### ISSUE THREAD

**Issue by otavepto** [Nemirtingas/ingame_overlay#19]
Currently on Dx12/Dx11 and probably others when the game's window is changed the overlay size stays the same and doesn't update.
This is (to my knowledge) the part which invokes the `OveralyHookReady` with state == `Reset`
https://github.com/Nemirtingas/ingame_overlay/blob/843888fd1fee1ed29cf74490a49dd9ece6d2eabe/src/Windows/DX12Hook.cpp#L457-L468

I'm relying solely on the callbacks [OverlayProc](https://github.com/Nemirtingas/ingame_overlay/blob/843888fd1fee1ed29cf74490a49dd9ece6d2eabe/include/InGameOverlay/RendererHook.h#L49) and [OverlayHookReady](https://github.com/Nemirtingas/ingame_overlay/blob/843888fd1fee1ed29cf74490a49dd9ece6d2eabe/include/InGameOverlay/RendererHook.h#L50) to get notifications, and as a workaround I have this code inside the callback for `OverlayHookReady`
```c++
ImGuiIO &io = ImGui::GetIO();
auto bd = ImGui::GetCurrentContext() ? (ImGui_ImplWin32_Data*)ImGui::GetIO().BackendPlatformUserData : nullptr;;
if (bd) {
    // Setup display size (every frame to accommodate for window resizing)
    RECT rect = { 0, 0, 0, 0 };
    ::GetClientRect(bd->hWnd, &rect);
    io.DisplaySize = ImVec2((float)(rect.right - rect.left), (float)(rect.bottom - rect.top));
}
```

The above code is copied from ImGui backend for win32
https://github.com/ocornut/imgui/blob/fbf45ad149b10ff8d9cb97aefe0dc5a9562fd66e/backends/imgui_impl_win32.cpp#L373-L382

I have 2 suggestions:
* Calling `ImGui_ImplWin32_NewFrame()` here before `ImGui::NewFrame()` https://github.com/Nemirtingas/ingame_overlay/blob/843888fd1fee1ed29cf74490a49dd9ece6d2eabe/src/Windows/DX12Hook.cpp#L384-L390
  You can see in the example of ImGui that this function is indeed called before `NewFrame`
  https://github.com/ocornut/imgui/blob/fbf45ad149b10ff8d9cb97aefe0dc5a9562fd66e/examples/example_win32_directx12/main.cpp#L140-L143

* Or, inside `ResizeTarget` after this line
  ```c++
  inst->_CreateRenderTargets(_this);
  ```
  You can update the window size, similar to the workaround I did.

Also wanted to ask, what's the point of invoking the callback `OverlayHookReady` with state == `Reset` ?, I didn't understand it very well.

I can submit a PR for suggestion 1 if you see this is a fitting change, I just don't know how to do this similarly for Linux/Mac, haven't looked at the other ImGui examples yet.

Please feel completely free to close this one if it's not fitting, out of scope, too much burden, etc...

**Comment by Nemirtingas** [comment]
Hi,
`OverlayHookState::Reset` is sent back to the user so that the user is aware that a window/swapchain size has changed. It allows the user to do things when the game has been resized.

As for the overlay not resizing, I don't know what you are talking about. This library is not about drawing a fullscreen overlay, it allows someone to draw an overlay.

If you want your overlay to be the same size as your game, you just set your window size, like in the example :

https://github.com/Nemirtingas/ingame_overlay/blob/master/tests/overlay_example/library_main.cpp#L113-L120

**Comment by Nemirtingas** [comment]
Well,
Maybe InGameOverlay has a bug, but if you have an issue, you should procure a reproductible example so people can work on the issue.

I'm trying to reproduce the issue right now, but I don't understand what might not be working.

**Comment by Nemirtingas** [comment]
No need to apologize. Better ask questions if you don't know something.

**Comment by Nemirtingas** [comment]
Learning something is never a waste of time.
Glad you figured it out. 👍
