### ISSUE TITLE
This is such a great project which I learned a lot from it.

### ISSUE THREAD

**Issue by eetoa** [Nemirtingas/ingame_overlay#2]
I just wanna thnx.
For dx12 games, I actually hooked the present vT function which works fine for me, but I learned the reset render state stuff from this project.
I am learning the vulkan API recent days planning to implement the vulkan imgui hook.

Great project~!

**Comment by Nemirtingas** [comment]
Thanks for the feedback. I'm still learning how the different rendering apis works but hooking Vulkan seems more complicated to setup for ImGui.
