### ISSUE TITLE
Overlay might be broken with dxvk on Direct3D 11 game

### ISSUE THREAD

**Issue by Edremon** [Nemirtingas/ingame_overlay#20]
I'm using Goldberg Steam Emulator fork by otavepto, recently he started using your project as a dependency and since then the overlay isn't working, I tried on multiple Direct3D 11 games and it worked on none, I have a single Direct3D 12 game and the overlay worked correctly on it.

After some troubleshooting, from what I understand the issue might be in your project. I do not know how to make some minimal reproduction example, but, I still think it's a good idea to investigate that issue.

Here the original issue: https://github.com/otavepto/gbe_fork/issues/94

**Comment by Nemirtingas** [comment]
I can't even start an app with DXVK without the overlay library.

**Comment by Nemirtingas** [comment]
The issue here is that DXVK uses both DXGI and D3D11. This library tries to intercept system's libraries, but DXVK blocks the D3D11 library loading, making the library create a DXVK DX11 device with a system DXGI Factory and crashes.

**Comment by Nemirtingas** [comment]
I am not the owner of Goldberg's code as such, I cannot tell what changes he made or not. DXVK is not supported, as NVidia streamline is not supported.
