### ISSUE TITLE
[Windows] Overlay Color Corruption

### ISSUE THREAD

**Issue by yU93r** [Nemirtingas/ingame_overlay#27]
In some DirectX 12 games (TLoU for example) the colors of the Overlay are corrupted. I am using the gbe_fork emulator using your library as an example.

![TLoU](https://github.com/Nemirtingas/ingame_overlay/assets/172665351/c95ce992-54b6-4c92-b0c7-c6e710a7d3b6)

**Comment by Nemirtingas** [comment]
Hi, I'm not the developper of gbe_fork, please provide a reproductible issue, else I'll have no choice but to close this.

**Comment by yU93r** [comment]
Actually, it's [not ](https://github.com/otavepto/gbe_fork/issues/185)because of Overlay. I think it's because of how you've hooked DirectX 12.

**Comment by Nemirtingas** [comment]
Also, the game uses NVidia Streamline, and it is not supported, see #7
