### ISSUE TITLE
Static runtime compilation seems not feasible

### ISSUE THREAD

**Issue by otavepto** [Nemirtingas/ingame_overlay#45]
Hello, sorry to bother you about this.
Just wanted to grab your attention that compilation statically seems not feasible with this commit f819c89e3b59dd7704eea8148c40c9f9be52284e

There is discussion about it [here](https://github.com/Detanup01/gbe_fork/issues/81) with a proposed fix for the CMake condition.

Here's also a complete verbose [compilation log](https://github.com/Detanup01/gbe_fork/actions/runs/11869155323/job/33079389991#step:9:177), you can see the detailed compilation and linking commands for verification.
The error happens in linking `mini_detour.lib(AArch64InstPrinter.obj) : error LNK2005: ___check_isa_support already defined in mini_detour.lib(AArch64Disassembler.obj)`

I know it's not helpful to just link a compilation log dump, but its quite difficult to pin point the reason. Please feel completely free to close this.

**Comment by Nemirtingas** [comment]
Static and dynamic builds work locally on my buildbot and on my pc. It is a strange issue on visual studio as it can be seen here:

The exact same commit works and doesn't, which is puzzling.

![image](https://github.com/user-attachments/assets/2093cbe7-8211-4bda-86f1-5e980e69987b)

![image](https://github.com/user-attachments/assets/e8c1319b-49e0-423e-9f65-e620ceb50e27)

**Comment by Nemirtingas** [comment]
"Fixed" here by removing all intrinsic when building with MSVC. But this will not make into the main branch.

**Comment by Nemirtingas** [comment]
#46

**Comment by otavepto** [comment]
I was checking this doc: https://learn.microsoft.com/en-us/cpp/intrinsics/compiler-intrinsics#remarks

I'll quote the suspicious parts
> Some intrinsics are available only as intrinsics, and some are available both in function and intrinsic implementations

Despite intrinsics being intended for communication with the compiler/optimizer, they can also be dedicated functions.
The next part says this
> The second is to use the [/Oi (Generate intrinsic functions)](https://learn.microsoft.com/en-us/cpp/build/reference/oi-generate-intrinsic-functions?view=msvc-170) compiler option, which makes all intrinsics on a given platform available

I created a simple x64 console app with CMake to check the default flags and `/Oi` was set to `No` in Visual Studio.
I'm not sure this is the reason but wanted to share the info with you nonetheless.

**Comment by Nemirtingas** [comment]
Microsoft being Microsoft. intrinsics were not even used in the code so...

**Comment by Nemirtingas** [comment]
Lets hope the new api will make it easier to work with the overlay 😄
