### ISSUE TITLE
Hook on macOS non-responsive

### ISSUE THREAD

**Issue by jaroen007** [Nemirtingas/ingame_overlay#6]
Hello,

I am getting very weird behavior when using the overlay_example to hook onto a game called Tibia (on macOS, using openGL). I can toggle the imgui menu fine but anything inside it is unresponsive (as long as the menu is active, nothing responds to input). besides that, the cursor goes from the default mac cursor to the custom tibia cursor repeatedly and very quickly (the game still recognizes inputs as long as the menu is not active). It looks like this:
![image](https://user-images.githubusercontent.com/5385460/193944991-c22997d9-4862-4dd4-8a9a-ae296bb5e9c0.png)

I don't have a lot of experience on this kinda stuff and im still learning it. I hope you can help me with this issue. 

EDIT: so i looked through a ton of the project some more and found i can simply always return false on the key combination callback to allow inputs to go through so that problem is solved. however, the problem with the cursor flickering and the imgui window not being responsive still persists

**Comment by Nemirtingas** [comment]
Hi, the overlay on MacOS is highly experimental. I don't have a proper Mac to test. If you always return false in the overlay callback, the library is running code as if the overlay was hidden and will send inputs to the game and ignore overlay inputs.
If the overlay flickers, look in your OverlayProc, you might be drawing it 1 frame on 2.

**Comment by jaroen007** [comment]
so what you are saying is that the overlay should be responsive if i don't return false? because it isn't. neither the game (which you explained) nor the overlay is responding to anything (which is the strange part). is there a way to make it listen to both game inputs and the imgui overlay button presses etc while the menu shows? 

also could the cursor blinking problem be a reason the imgui overlay is not responding to inputs when returning true?

**Comment by Nemirtingas** [comment]
Yes, it should be responsive if you don't return false. Did you try the macos_opengl2 example app ? If you want both the game and the overlay to listen to inputs, you should change the code at https://github.com/Nemirtingas/ingame_overlay/blob/7464c28207fc2ca12e1d39bfb18246b479d708e7/src/macosx/NSView_Hook.mm#L142-L147
into 
```
        ImGui_ImplOSX_HandleEvent(event, view);

        return event;
```

**Comment by jaroen007** [comment]
i have not tried changing that yet but i will later today (ill let you know). something else i don't quite get is that im hooking with openGL. does the NSView_Hook.mm file u are referencing actually get used? aren't openGL and NS two seperate hooking methods?

**Comment by Nemirtingas** [comment]
They are different, but NSView_Hook is the event and window hook, while OpenGL_Hook is the OpenGL renderer hook, there will be a Metal_Hook too, but the Metal_Hook will still use NSView_Hook to hook events. Metal and OpenGL are renderers and I hook them to be able to draw stuff on the application's Window.

**Comment by jaroen007** [comment]
I tried your solution and i can now interact with the game even when returning true. however, no matter what i do i cannot interact with the imgui window (not moving it, not clicking on a button, etc..) do you have any ideas what the problem could be with this? (could it be the mouse flickering?). 

if you have discord you could add me so we can chat easier: Neoray#9573 I could also help with programming things for the mac section of it once i get the hang of how it all works :)

**Comment by Nemirtingas** [comment]
The overlay mouse Y coordinate was wrong and will be fixed by: https://github.com/Nemirtingas/imgui/commit/2e36b12af64b07c26142c23687202c6dde86e12f

**Comment by Nemirtingas** [comment]
Fixed in https://github.com/Nemirtingas/ingame_overlay/commit/5203c1c10cf340d5f989c1a292707a5444353feb
Added an API to enable/disable app/overlay inputs: https://github.com/Nemirtingas/ingame_overlay/blob/master/include/ingame_overlay/Renderer_Hook.h#L60-L78
